### ISSUE TITLE
gar keine edges

### ISSUE THREAD

**Issue by ploth** [ploth/lineDetection#1]
hattest du es nicht mal geschafft edges zu erkennen aus den random vektor?
ich weiß nicht genau was anders ist. aber das klappt irgendwie nicht mehr. dafür füllt sich der vektor jetzt mit einer scanline aus dem richtigen bild.

**Comment by malterik** [comment]
Jo, der Algorithmus hat irgendwas erkannt. Ob das nun wirklich die edges waren, kann ich dir nicht sagen. Aber im Ergebnis Vektor war irgendwas drin.

**Comment by ploth** [comment]
jo hab es auch wieder hinbekommen - danke. will jetzt einmal über das ganze bild iterieren und die pixel einfärben. mal schauen was passiert.

**Comment by ploth** [comment]
keine ahnung. opencv will gar nicht mehr. kann mir nichtmal mehr ein bild anzeigen lassen. bekomme segmentation faults. ende aus.

**Comment by malterik** [comment]
Hmm komisch. Ins Bett gehen und morgen nochmal :D 

 

Von: Pascal Loth [mailto:notifications@github.com] 
Gesendet: Mittwoch, 25. März 2015 20:43
An: ploth/lineDetection
Cc: Erik Schröder
Betreff: Re: [lineDetection] gar keine edges (#1)

 

keine ahnung. opencv will gar nicht mehr. kann mir nichtmal mehr ein bild anzeigen lassen. bekomme segmentation faults. ende aus.
